DISTFILES += \
    lib/StanfordCPPLib/addr2line.exe \
    lib/StanfordCPPLib/addr2line64.exe \
    lib/StanfordCPPLib/iconstrip.png \
    lib/addr2line.exe \
    lib/readme.txt \
    lib/spl.jar

HEADERS += \
    lib/StanfordCPPLib/StanfordCPPLib/collections/basicgraph.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/collections.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/dawglexicon.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/deque.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/functional.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/graph.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/grid.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/gridlocation.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/hashcode.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/hashmap.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/hashset.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/lexicon.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/linkedhashmap.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/linkedhashset.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/linkedlist.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/map.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/pqueue.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/priorityqueue.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/queue.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/set.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/shuffle.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/sparsegrid.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/stack.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/stl.h \
    lib/StanfordCPPLib/StanfordCPPLib/collections/vector.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/console.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/consoletext.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gbrowserpane.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gbufferedimage.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gbutton.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcanvas.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcheckbox.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gchooser.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gclipboard.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcolor.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcolorchooser.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gconsolewindow.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcontainer.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gdiffgui.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gdiffimage.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gdownloader.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gdrawingsurface.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gevent.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/geventqueue.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gevents.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gfilechooser.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gfont.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gfontchooser.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gformattedpane.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/ginputpanel.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/ginteractor.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/ginteractors.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/glabel.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/glayout.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gobjects.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gobservable.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/goptionpane.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gradiobutton.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gscrollbar.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gscrollpane.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gslider.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gspacer.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtable.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtextarea.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtextfield.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gthread.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtimer.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtypes.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gwindow.h \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/qtgui.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/base64.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/bitstream.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/filelib.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/plainconsole.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/rapidxml.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/server.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/simpio.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/tokenscanner.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/urlstream.h \
    lib/StanfordCPPLib/StanfordCPPLib/io/xmlutils.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/consolestreambuf.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/echoinputstreambuf.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/foreachpatch.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/forwardingstreambuf.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/headless.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/init.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/initstudent.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/limitoutputstreambuf.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/multimain.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/precompiled.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/randompatch.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/static.h \
    lib/StanfordCPPLib/StanfordCPPLib/private/version.h \
    lib/StanfordCPPLib/StanfordCPPLib/system/call_stack.h \
    lib/StanfordCPPLib/StanfordCPPLib/system/error.h \
    lib/StanfordCPPLib/StanfordCPPLib/system/exceptions.h \
    lib/StanfordCPPLib/StanfordCPPLib/system/os.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/bigfloat.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/biginteger.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/complex.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/diff.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/direction.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/foreach.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/gmath.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/intrange.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/managed.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/memory.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/note.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/observable.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/point.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/random.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/recursion.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/regexpr.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/require.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/sound.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/stringutils.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/strlib.h \
    lib/StanfordCPPLib/StanfordCPPLib/util/timer.h \
    lib/StanfordCPPLib/base64.h \
    lib/StanfordCPPLib/basicgraph.h \
    lib/StanfordCPPLib/bitstream.h \
    lib/StanfordCPPLib/compare.h \
    lib/StanfordCPPLib/console.h \
    lib/StanfordCPPLib/dawglexicon.h \
    lib/StanfordCPPLib/deque.h \
    lib/StanfordCPPLib/direction.h \
    lib/StanfordCPPLib/error.h \
    lib/StanfordCPPLib/exceptions.h \
    lib/StanfordCPPLib/filelib.h \
    lib/StanfordCPPLib/foreach.h \
    lib/StanfordCPPLib/gbufferedimage.h \
    lib/StanfordCPPLib/gevents.h \
    lib/StanfordCPPLib/gfilechooser.h \
    lib/StanfordCPPLib/ginteractors.h \
    lib/StanfordCPPLib/gmath.h \
    lib/StanfordCPPLib/gobjects.h \
    lib/StanfordCPPLib/goptionpane.h \
    lib/StanfordCPPLib/graph.h \
    lib/StanfordCPPLib/grid.h \
    lib/StanfordCPPLib/gtable.h \
    lib/StanfordCPPLib/gtimer.h \
    lib/StanfordCPPLib/gtypes.h \
    lib/StanfordCPPLib/gwindow.h \
    lib/StanfordCPPLib/hashcode.h \
    lib/StanfordCPPLib/hashmap.h \
    lib/StanfordCPPLib/hashset.h \
    lib/StanfordCPPLib/lexicon.h \
    lib/StanfordCPPLib/linkedhashmap.h \
    lib/StanfordCPPLib/linkedhashset.h \
    lib/StanfordCPPLib/linkedlist.h \
    lib/StanfordCPPLib/map.h \
    lib/StanfordCPPLib/observable.h \
    lib/StanfordCPPLib/plainconsole.h \
    lib/StanfordCPPLib/platform.h \
    lib/StanfordCPPLib/point.h \
    lib/StanfordCPPLib/pqueue.h \
    lib/StanfordCPPLib/private/foreachpatch.h \
    lib/StanfordCPPLib/private/main.h \
    lib/StanfordCPPLib/private/randompatch.h \
    lib/StanfordCPPLib/private/tokenpatch.h \
    lib/StanfordCPPLib/private/tplatform.h \
    lib/StanfordCPPLib/private/version.h \
    lib/StanfordCPPLib/queue.h \
    lib/StanfordCPPLib/random.h \
    lib/StanfordCPPLib/regexpr.h \
    lib/StanfordCPPLib/server.h \
    lib/StanfordCPPLib/set.h \
    lib/StanfordCPPLib/shuffle.h \
    lib/StanfordCPPLib/simpio.h \
    lib/StanfordCPPLib/sound.h \
    lib/StanfordCPPLib/sparsegrid.h \
    lib/StanfordCPPLib/stack.h \
    lib/StanfordCPPLib/stacktrace/call_stack.h \
    lib/StanfordCPPLib/stacktrace/stack_exception.h \
    lib/StanfordCPPLib/strlib.h \
    lib/StanfordCPPLib/timer.h \
    lib/StanfordCPPLib/tokenscanner.h \
    lib/StanfordCPPLib/urlstream.h \
    lib/StanfordCPPLib/vector.h

SOURCES += \
    lib/StanfordCPPLib/StanfordCPPLib/collections/basicgraph.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/collections/collections.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/collections/dawglexicon.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/collections/gridlocation.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/collections/hashcode.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/collections/lexicon.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/collections/shuffle.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/collections/stl.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/console.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gbrowserpane.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gbutton.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcanvas.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcheckbox.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gchooser.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gclipboard.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcolor.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcolorchooser.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gconsolewindow.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gcontainer.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gdiffgui.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gdiffimage.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gdownloader.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gdrawingsurface.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gevent.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/geventqueue.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gfilechooser.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gfont.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gfontchooser.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/ginputpanel.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/ginteractor.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/glabel.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/glayout.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gobjects.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gobservable.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/goptionpane.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gradiobutton.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gscrollbar.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gscrollpane.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gslider.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gspacer.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtable.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtextarea.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtextfield.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gthread.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtimer.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gtypes.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/gwindow.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/graphics/qtgui.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/base64.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/bitstream.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/filelib.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/plainconsole.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/server.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/simpio.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/tokenscanner.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/urlstream.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/io/xmlutils.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/private/filelibunix.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/private/filelibwindows.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/private/init.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/private/mainwrapper.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/private/multimain.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/private/version.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/system/call_stack_gcc.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/system/call_stack_windows.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/system/error.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/system/exceptions.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/system/os.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/bigfloat.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/biginteger.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/complex.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/diff.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/direction.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/gmath.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/intrange.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/memory.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/note.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/point.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/random.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/recursion.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/regexpr.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/require.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/sound.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/stringutils.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/strlib.cpp \
    lib/StanfordCPPLib/StanfordCPPLib/util/timer.cpp \
    lib/StanfordCPPLib/base64.cpp \
    lib/StanfordCPPLib/basicgraph.cpp \
    lib/StanfordCPPLib/bitstream.cpp \
    lib/StanfordCPPLib/console.cpp \
    lib/StanfordCPPLib/dawglexicon.cpp \
    lib/StanfordCPPLib/direction.cpp \
    lib/StanfordCPPLib/error.cpp \
    lib/StanfordCPPLib/exceptions.cpp \
    lib/StanfordCPPLib/filelib.cpp \
    lib/StanfordCPPLib/gbufferedimage.cpp \
    lib/StanfordCPPLib/gevents.cpp \
    lib/StanfordCPPLib/gfilechooser.cpp \
    lib/StanfordCPPLib/ginteractors.cpp \
    lib/StanfordCPPLib/gmath.cpp \
    lib/StanfordCPPLib/gobjects.cpp \
    lib/StanfordCPPLib/goptionpane.cpp \
    lib/StanfordCPPLib/gtable.cpp \
    lib/StanfordCPPLib/gtimer.cpp \
    lib/StanfordCPPLib/gtypes.cpp \
    lib/StanfordCPPLib/gwindow.cpp \
    lib/StanfordCPPLib/hashcode.cpp \
    lib/StanfordCPPLib/lexicon.cpp \
    lib/StanfordCPPLib/main.cpp \
    lib/StanfordCPPLib/observable.cpp \
    lib/StanfordCPPLib/plainconsole.cpp \
    lib/StanfordCPPLib/platform.cpp \
    lib/StanfordCPPLib/point.cpp \
    lib/StanfordCPPLib/random.cpp \
    lib/StanfordCPPLib/regexpr.cpp \
    lib/StanfordCPPLib/server.cpp \
    lib/StanfordCPPLib/shuffle.cpp \
    lib/StanfordCPPLib/simpio.cpp \
    lib/StanfordCPPLib/sound.cpp \
    lib/StanfordCPPLib/stacktrace/call_stack_gcc.cpp \
    lib/StanfordCPPLib/stacktrace/call_stack_windows.cpp \
    lib/StanfordCPPLib/startup.cpp \
    lib/StanfordCPPLib/strlib.cpp \
    lib/StanfordCPPLib/timer.cpp \
    lib/StanfordCPPLib/tokenscanner.cpp \
    lib/StanfordCPPLib/urlstream.cpp \
    lib/StanfordCPPLib/version.cpp \
    src/main.cpp
